# Form implementation generated from reading ui file 'xu_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        self.boxNotePad = QtWidgets.QGroupBox(parent=Form)
        self.boxNotePad.setGeometry(QtCore.QRect(570, 10, 221, 481))
        self.boxNotePad.setObjectName("boxNotePad")
        self.textNotePad = QtWidgets.QTextEdit(parent=self.boxNotePad)
        self.textNotePad.setGeometry(QtCore.QRect(10, 20, 201, 411))
        self.textNotePad.setObjectName("textNotePad")
        self.buttonSaveNote = QtWidgets.QPushButton(parent=self.boxNotePad)
        self.buttonSaveNote.setGeometry(QtCore.QRect(70, 440, 81, 26))
        self.buttonSaveNote.setObjectName("buttonSaveNote")
        self.boxWorkSpace = QtWidgets.QGroupBox(parent=Form)
        self.boxWorkSpace.setGeometry(QtCore.QRect(10, 10, 551, 481))
        self.boxWorkSpace.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.boxWorkSpace.setObjectName("boxWorkSpace")
        self.boxInformation = QtWidgets.QGroupBox(parent=self.boxWorkSpace)
        self.boxInformation.setGeometry(QtCore.QRect(10, 40, 531, 181))
        self.boxInformation.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.boxInformation.setObjectName("boxInformation")
        self.labelScale = QtWidgets.QLabel(parent=self.boxInformation)
        self.labelScale.setGeometry(QtCore.QRect(70, 30, 101, 21))
        self.labelScale.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelScale.setObjectName("labelScale")
        self.labelKeysOrigin = QtWidgets.QLabel(parent=self.boxInformation)
        self.labelKeysOrigin.setGeometry(QtCore.QRect(70, 70, 101, 21))
        self.labelKeysOrigin.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelKeysOrigin.setObjectName("labelKeysOrigin")
        self.labelKeysOnScale = QtWidgets.QLabel(parent=self.boxInformation)
        self.labelKeysOnScale.setGeometry(QtCore.QRect(70, 110, 101, 21))
        self.labelKeysOnScale.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelKeysOnScale.setObjectName("labelKeysOnScale")
        self.lineKeyOrigin = QtWidgets.QLineEdit(parent=self.boxInformation)
        self.lineKeyOrigin.setGeometry(QtCore.QRect(180, 70, 251, 20))
        self.lineKeyOrigin.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineKeyOrigin.setFrame(False)
        self.lineKeyOrigin.setReadOnly(True)
        self.lineKeyOrigin.setObjectName("lineKeyOrigin")
        self.lineKeyOnScale = QtWidgets.QLineEdit(parent=self.boxInformation)
        self.lineKeyOnScale.setGeometry(QtCore.QRect(180, 110, 251, 20))
        self.lineKeyOnScale.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineKeyOnScale.setFrame(False)
        self.lineKeyOnScale.setReadOnly(True)
        self.lineKeyOnScale.setObjectName("lineKeyOnScale")
        self.comboRootNote = QtWidgets.QComboBox(parent=self.boxInformation)
        self.comboRootNote.setGeometry(QtCore.QRect(180, 30, 51, 22))
        self.comboRootNote.setObjectName("comboRootNote")
        self.comboScale = QtWidgets.QComboBox(parent=self.boxInformation)
        self.comboScale.setGeometry(QtCore.QRect(240, 30, 191, 22))
        self.comboScale.setObjectName("comboScale")
        self.label_scale = QtWidgets.QLabel(parent=self.boxInformation)
        self.label_scale.setGeometry(QtCore.QRect(40, 140, 451, 28))
        self.label_scale.setStyleSheet("")
        self.label_scale.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_scale.setObjectName("label_scale")
        self.boxKeyboard = QtWidgets.QGroupBox(parent=self.boxWorkSpace)
        self.boxKeyboard.setGeometry(QtCore.QRect(10, 260, 531, 211))
        self.boxKeyboard.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.boxKeyboard.setStyleSheet("QGroupBox:focus {\n"
"    border: 2px dotted #00d4ff;\n"
"    margin: 8px 0 0 0;\n"
"    color: #00d4ff;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}")
        self.boxKeyboard.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.boxKeyboard.setObjectName("boxKeyboard")
        self.buttonWhiteKey_1 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_1.setGeometry(QtCore.QRect(70, 90, 21, 111))
        self.buttonWhiteKey_1.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_1.setStyleSheet("QPushButton {\n"
"    background-color: #fffddd;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_1.setObjectName("buttonWhiteKey_1")
        self.buttonWhiteKey_2 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_2.setGeometry(QtCore.QRect(90, 90, 21, 111))
        self.buttonWhiteKey_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_2.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_2.setObjectName("buttonWhiteKey_2")
        self.buttonWhiteKey_3 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_3.setGeometry(QtCore.QRect(110, 90, 21, 111))
        self.buttonWhiteKey_3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_3.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_3.setObjectName("buttonWhiteKey_3")
        self.buttonWhiteKey_4 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_4.setGeometry(QtCore.QRect(130, 90, 21, 111))
        self.buttonWhiteKey_4.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_4.setObjectName("buttonWhiteKey_4")
        self.buttonWhiteKey_5 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_5.setGeometry(QtCore.QRect(150, 90, 21, 111))
        self.buttonWhiteKey_5.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_5.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_5.setObjectName("buttonWhiteKey_5")
        self.buttonWhiteKey_6 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_6.setGeometry(QtCore.QRect(170, 90, 21, 111))
        self.buttonWhiteKey_6.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_6.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_6.setObjectName("buttonWhiteKey_6")
        self.buttonWhiteKey_7 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_7.setGeometry(QtCore.QRect(190, 90, 21, 111))
        self.buttonWhiteKey_7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_7.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_7.setObjectName("buttonWhiteKey_7")
        self.buttonWhiteKey_8 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_8.setGeometry(QtCore.QRect(210, 90, 21, 111))
        self.buttonWhiteKey_8.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_8.setStyleSheet("QPushButton {\n"
"    background-color: #fffddd;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_8.setObjectName("buttonWhiteKey_8")
        self.buttonWhiteKey_9 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_9.setGeometry(QtCore.QRect(230, 90, 21, 111))
        self.buttonWhiteKey_9.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_9.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_9.setObjectName("buttonWhiteKey_9")
        self.buttonWhiteKey_10 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_10.setGeometry(QtCore.QRect(250, 90, 21, 111))
        self.buttonWhiteKey_10.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_10.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_10.setObjectName("buttonWhiteKey_10")
        self.buttonWhiteKey_11 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_11.setGeometry(QtCore.QRect(270, 90, 21, 111))
        self.buttonWhiteKey_11.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_11.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_11.setObjectName("buttonWhiteKey_11")
        self.buttonWhiteKey_12 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_12.setGeometry(QtCore.QRect(290, 90, 21, 111))
        self.buttonWhiteKey_12.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_12.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_12.setObjectName("buttonWhiteKey_12")
        self.buttonWhiteKey_13 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_13.setGeometry(QtCore.QRect(310, 90, 21, 111))
        self.buttonWhiteKey_13.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_13.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_13.setObjectName("buttonWhiteKey_13")
        self.buttonWhiteKey_14 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_14.setGeometry(QtCore.QRect(330, 90, 21, 111))
        self.buttonWhiteKey_14.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_14.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_14.setObjectName("buttonWhiteKey_14")
        self.buttonWhiteKey_15 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_15.setGeometry(QtCore.QRect(350, 90, 21, 111))
        self.buttonWhiteKey_15.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_15.setStyleSheet("QPushButton {\n"
"    background-color: #fffddd;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_15.setObjectName("buttonWhiteKey_15")
        self.buttonWhiteKey_16 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_16.setGeometry(QtCore.QRect(370, 90, 21, 111))
        self.buttonWhiteKey_16.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_16.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_16.setObjectName("buttonWhiteKey_16")
        self.buttonWhiteKey_17 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_17.setGeometry(QtCore.QRect(390, 90, 21, 111))
        self.buttonWhiteKey_17.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_17.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_17.setObjectName("buttonWhiteKey_17")
        self.buttonWhiteKey_18 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_18.setGeometry(QtCore.QRect(410, 90, 21, 111))
        self.buttonWhiteKey_18.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_18.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_18.setObjectName("buttonWhiteKey_18")
        self.buttonWhiteKey_19 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonWhiteKey_19.setGeometry(QtCore.QRect(430, 90, 21, 111))
        self.buttonWhiteKey_19.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonWhiteKey_19.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d0d0d0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e2faff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #97efff;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid #00c1e4;\n"
"}\n"
"")
        self.buttonWhiteKey_19.setObjectName("buttonWhiteKey_19")
        self.buttonBlackKey_1 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_1.setGeometry(QtCore.QRect(80, 60, 21, 71))
        self.buttonBlackKey_1.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_1.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_1.setObjectName("buttonBlackKey_1")
        self.buttonBlackKey_2 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_2.setGeometry(QtCore.QRect(100, 60, 21, 71))
        self.buttonBlackKey_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_2.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_2.setObjectName("buttonBlackKey_2")
        self.buttonBlackKey_3 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_3.setGeometry(QtCore.QRect(140, 60, 21, 71))
        self.buttonBlackKey_3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_3.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_3.setObjectName("buttonBlackKey_3")
        self.buttonBlackKey_4 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_4.setGeometry(QtCore.QRect(160, 60, 21, 71))
        self.buttonBlackKey_4.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_4.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_4.setObjectName("buttonBlackKey_4")
        self.buttonBlackKey_5 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_5.setGeometry(QtCore.QRect(180, 60, 21, 71))
        self.buttonBlackKey_5.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_5.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_5.setObjectName("buttonBlackKey_5")
        self.buttonBlackKey_6 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_6.setGeometry(QtCore.QRect(220, 60, 21, 71))
        self.buttonBlackKey_6.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_6.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_6.setObjectName("buttonBlackKey_6")
        self.buttonBlackKey_7 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_7.setGeometry(QtCore.QRect(240, 60, 21, 71))
        self.buttonBlackKey_7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_7.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_7.setObjectName("buttonBlackKey_7")
        self.buttonBlackKey_8 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_8.setGeometry(QtCore.QRect(280, 60, 21, 71))
        self.buttonBlackKey_8.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_8.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_8.setObjectName("buttonBlackKey_8")
        self.buttonBlackKey_9 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_9.setGeometry(QtCore.QRect(300, 60, 21, 71))
        self.buttonBlackKey_9.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_9.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_9.setObjectName("buttonBlackKey_9")
        self.buttonBlackKey_10 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_10.setGeometry(QtCore.QRect(320, 60, 21, 71))
        self.buttonBlackKey_10.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_10.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_10.setObjectName("buttonBlackKey_10")
        self.buttonBlackKey_11 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_11.setGeometry(QtCore.QRect(360, 60, 21, 71))
        self.buttonBlackKey_11.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_11.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_11.setObjectName("buttonBlackKey_11")
        self.buttonBlackKey_12 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_12.setGeometry(QtCore.QRect(380, 60, 21, 71))
        self.buttonBlackKey_12.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_12.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_12.setObjectName("buttonBlackKey_12")
        self.buttonBlackKey_13 = QtWidgets.QPushButton(parent=self.boxKeyboard)
        self.buttonBlackKey_13.setGeometry(QtCore.QRect(420, 60, 21, 71))
        self.buttonBlackKey_13.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.buttonBlackKey_13.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border: 1px solid #b0b0b0;\n"
"    padding: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #585858;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #37c0d9;\n"
"}\n"
"QPushButton:focus {\n"
"    border: 1px solid;\n"
"}\n"
"")
        self.buttonBlackKey_13.setObjectName("buttonBlackKey_13")
        self.buttonSwitch = QtWidgets.QPushButton(parent=self.boxWorkSpace)
        self.buttonSwitch.setGeometry(QtCore.QRect(220, 230, 111, 26))
        self.buttonSwitch.setObjectName("buttonSwitch")
        self.label_info = QtWidgets.QLabel(parent=self.boxWorkSpace)
        self.label_info.setGeometry(QtCore.QRect(110, 10, 331, 28))
        self.label_info.setStyleSheet("color: #a0a0a0;")
        self.label_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.comboSound = QtWidgets.QComboBox(parent=self.boxWorkSpace)
        self.comboSound.setGeometry(QtCore.QRect(80, 230, 131, 24))
        self.comboSound.setObjectName("comboSound")
        self.labelSoundLib = QtWidgets.QLabel(parent=self.boxWorkSpace)
        self.labelSoundLib.setGeometry(QtCore.QRect(10, 230, 63, 21))
        self.labelSoundLib.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelSoundLib.setObjectName("labelSoundLib")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Simple Piano"))
        self.boxNotePad.setTitle(_translate("Form", "Note Pad"))
        self.buttonSaveNote.setText(_translate("Form", "Save"))
        self.boxWorkSpace.setTitle(_translate("Form", "Work Space"))
        self.boxInformation.setTitle(_translate("Form", "Information"))
        self.labelScale.setText(_translate("Form", "Scale :"))
        self.labelKeysOrigin.setText(_translate("Form", "Keys origin :"))
        self.labelKeysOnScale.setText(_translate("Form", "Keys on scale :"))
        self.label_scale.setText(_translate("Form", "Scale :"))
        self.boxKeyboard.setTitle(_translate("Form", "Keyboard"))
        self.buttonWhiteKey_1.setText(_translate("Form", "\n"
"Z"))
        self.buttonWhiteKey_2.setText(_translate("Form", "\n"
"X"))
        self.buttonWhiteKey_3.setText(_translate("Form", "\n"
"C"))
        self.buttonWhiteKey_4.setText(_translate("Form", "\n"
"V"))
        self.buttonWhiteKey_5.setText(_translate("Form", "\n"
"B"))
        self.buttonWhiteKey_6.setText(_translate("Form", "\n"
"N"))
        self.buttonWhiteKey_7.setText(_translate("Form", "\n"
"M"))
        self.buttonWhiteKey_8.setText(_translate("Form", "\n"
"\n"
"Q\n"
","))
        self.buttonWhiteKey_9.setText(_translate("Form", "\n"
"\n"
"W\n"
"."))
        self.buttonWhiteKey_10.setText(_translate("Form", "\n"
"\n"
"E\n"
"/"))
        self.buttonWhiteKey_11.setText(_translate("Form", "\n"
"R"))
        self.buttonWhiteKey_12.setText(_translate("Form", "\n"
"T"))
        self.buttonWhiteKey_13.setText(_translate("Form", "\n"
"Y"))
        self.buttonWhiteKey_14.setText(_translate("Form", "\n"
"U"))
        self.buttonWhiteKey_15.setText(_translate("Form", "\n"
"I"))
        self.buttonWhiteKey_16.setText(_translate("Form", "\n"
"O"))
        self.buttonWhiteKey_17.setText(_translate("Form", "\n"
"P"))
        self.buttonWhiteKey_18.setText(_translate("Form", "\n"
"["))
        self.buttonWhiteKey_19.setText(_translate("Form", "\n"
"]"))
        self.buttonBlackKey_1.setText(_translate("Form", "S"))
        self.buttonBlackKey_2.setText(_translate("Form", "D"))
        self.buttonBlackKey_3.setText(_translate("Form", "G"))
        self.buttonBlackKey_4.setText(_translate("Form", "H"))
        self.buttonBlackKey_5.setText(_translate("Form", "J"))
        self.buttonBlackKey_6.setText(_translate("Form", "2\n"
"L"))
        self.buttonBlackKey_7.setText(_translate("Form", "3\n"
";"))
        self.buttonBlackKey_8.setText(_translate("Form", "5"))
        self.buttonBlackKey_9.setText(_translate("Form", "6"))
        self.buttonBlackKey_10.setText(_translate("Form", "7"))
        self.buttonBlackKey_11.setText(_translate("Form", "9"))
        self.buttonBlackKey_12.setText(_translate("Form", "0"))
        self.buttonBlackKey_13.setText(_translate("Form", "="))
        self.buttonSwitch.setText(_translate("Form", "Switch to Scale"))
        self.label_info.setText(_translate("Form", "[Info]"))
        self.labelSoundLib.setText(_translate("Form", "SoundLib :"))
